#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Optional


# =============================================================================
# User configuration area
# =============================================================================

# Number of sampled parameters: para0 ... para(N_PARAM-1)
N_PARAM = 15

# Default output C file name.
OUTPUT_C_FILE = "SIMU_RV/user_prior.c"

# Default prior for parameters not explicitly listed in PRIOR_TYPES.
DEFAULT_PRIOR = "uniform"

# Specify non-uniform priors here. Unlisted parameters use DEFAULT_PRIOR.
# Allowed values: "uniform", "beta", "trunc_gaussian".
# Example matching the uploaded 17-parameter user_prior.c style:
#   para0: truncated Gaussian
#   para1: Beta(0.867, 3.03)
#   para7: truncated Gaussian
#   para8: Beta(0.867, 3.03)
PRIOR_TYPES: Dict[int, str] = {
    0: "trunc_gaussian",
    1: "beta",
    5: "trunc_gaussian",
    6: "beta",
}

SUPPORTED_PRIORS = {"uniform", "beta", "trunc_gaussian"}


# =============================================================================
# Utility functions for this Python generator
# =============================================================================

def parse_index_list(text: Optional[str]) -> List[int]:
    """Parse strings like '0,1,7' or '0 1 7' into integer indices."""
    if text is None or text.strip() == "":
        return []
    normalized = text.replace(",", " ")
    out: List[int] = []
    for item in normalized.split():
        idx = int(item)
        out.append(idx)
    return out


def validate_prior_map(n_param: int, prior_map: Dict[int, str]) -> None:
    """Validate parameter count and prior specification."""
    if n_param <= 0:
        raise ValueError("N_PARAM must be a positive integer.")

    for idx, kind in prior_map.items():
        if idx < 0 or idx >= n_param:
            raise ValueError(
                f"Invalid parameter index {idx}. Valid range is 0 to {n_param - 1}."
            )
        if kind not in SUPPORTED_PRIORS:
            raise ValueError(
                f"Invalid prior type {kind!r} for para{idx}. "
                f"Allowed: {sorted(SUPPORTED_PRIORS)}"
            )


def build_prior_map(
    n_param: int,
    base_map: Dict[int, str],
    beta_indices: Optional[Iterable[int]] = None,
    trunc_gaussian_indices: Optional[Iterable[int]] = None,
    uniform_indices: Optional[Iterable[int]] = None,
) -> Dict[int, str]:
    """Build the final prior map. CLI choices override the top-file config."""
    prior_map = {i: DEFAULT_PRIOR for i in range(n_param)}

    for idx, kind in base_map.items():
        if 0 <= idx < n_param:
            prior_map[idx] = kind

    if beta_indices is not None:
        for idx in beta_indices:
            prior_map[idx] = "beta"

    if trunc_gaussian_indices is not None:
        for idx in trunc_gaussian_indices:
            prior_map[idx] = "trunc_gaussian"

    if uniform_indices is not None:
        for idx in uniform_indices:
            prior_map[idx] = "uniform"

    validate_prior_map(n_param, prior_map)
    return prior_map


def c_header_autogenerated(n_param: int, prior_map: Dict[int, str]) -> str:
    """Generate the top comment block for the C file."""
    lines = []
    lines.append("///////////////////////////////////")
    lines.append("// Auto-generated user_prior.c")
    lines.append("// Generated by generate_user_prior.py")
    lines.append("//")
    lines.append(f"// Number of parameters: {n_param}")
    lines.append("// Prior assignment:")
    for i in range(n_param):
        lines.append(f"//   para{i}: {prior_map[i]}")
    lines.append("//")
    lines.append("// Do not edit repetitive blocks by hand unless necessary.")
    lines.append("// Change generate_user_prior.py and regenerate this file instead.")
    lines.append("///////////////////////////////////")
    return "\n".join(lines)


def section(title: str) -> str:
    """Generate a visual section header for the C file."""
    return f"""


//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
////// {title}
//////////////////////////////////////////////////////////////////////////////
""".rstrip()


def declarations(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 1"))
    lines.append("////// define how many parameters in the model")
    lines.append("////// their values are read from input files by read_parm_range(char *path)")
    lines.append("//")
    for i in range(n_param):
        lines.append(f"double para{i}_min;")
    lines.append("//")
    for i in range(n_param):
        lines.append(f"double para{i}_max;")
    lines.append("//")
    return "\n".join(lines)


def read_parm_range(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 2: read prior range"))
    lines.append("///////   NOTE: Input Min and Max in default.")
    lines.append("///////   NOTE: Add your own control para (mean, std, etc) in case of needed.")
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    lines.append("void read_parm_range(char *path)")
    lines.append("{")
    lines.append("    char *para_line;")
    lines.append("    char *para_name;")
    lines.append("    char dummy[DEST_SIZE] = {0};")
    lines.append("    char *read_onepara(char *path, char *para_name);")
    lines.append("")
    for i in range(n_param):
        lines.append(f"    ////////////////// para{i}")
        lines.append(f"    para_name = \"para{i}_max\";")
        lines.append("    para_line = read_onepara(path, para_name);")
        lines.append(f"    sscanf(para_line, \"%[^:]:%lf\", dummy, &para{i}_max);")
        lines.append("    free(para_line);")
        lines.append("    para_line = NULL;")
        lines.append(f"    para_name = \"para{i}_min\";")
        lines.append("    para_line = read_onepara(path, para_name);")
        lines.append(f"    sscanf(para_line, \"%[^:]:%lf\", dummy, &para{i}_min);")
        lines.append("    free(para_line);")
        lines.append("    para_line = NULL;")
        lines.append("    //")
    lines.append("}")
    return "\n".join(lines)


def init_functions(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 3: initialize prior, part 1"))
    lines.append("///////   NOTE: uniform initialization in default.")
    lines.append("///////   NOTE: Specify your own init function in case of needed.")
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    for i in range(n_param):
        lines.append(f"double para{i}_init(double para{i}_min, double para{i}_max)")
        lines.append("{")
        lines.append(f"    double para{i};")
        lines.append(f"    para{i} = r8_unif_ab( para{i}_min, para{i}_max );")
        lines.append(f"    return para{i};")
        lines.append("}")
        lines.append("//")
    return "\n".join(lines)


def init_parm_set(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 4 initialize, part 2"))
    lines.append("///////   NOTE: uniform initialization in default.")
    lines.append("///////   NOTE: Specify your own init function in case of needed.")
    lines.append("//")
    lines.append("// set init parameter at N_ITER = 0")
    lines.append("void init_parm_set(int seed, double* chain_parm)")
    lines.append("{")
    lines.append("    // rand seed")
    lines.append("    srand48(seed);")
    lines.append("    //")
    lines.append("    char *input_file;")
    lines.append("    input_file = \"input.ini\";")
    lines.append("    // read the range")
    lines.append("    read_parm_range(input_file);")
    lines.append("    //")
    for i in range(n_param):
        lines.append(f"    chain_parm[{i}] = para{i}_init(para{i}_min, para{i}_max);")
    lines.append("    //")
    lines.append("    ////// set sigma tuning range of parms")
    lines.append("    sigma_parm_min = (double *) malloc(sizeof(double)*N_parm);")
    lines.append("    sigma_parm_max = (double *) malloc(sizeof(double)*N_parm);")
    lines.append("    calc_sigma_scale_boundary(sigma_scale_min, sigma_scale_max, sigma_parm_min, sigma_parm_max);")
    lines.append("}")
    return "\n".join(lines)


def sigma_boundary(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 5: calc the scaling boundary of each para"))
    lines.append("////////////////////////////////////////////")
    lines.append("////////////////////////////////////////////")
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    lines.append("int calc_sigma_scale_boundary(double sigma_scale_min, double sigma_scale_max, double *sigma_parm_min, double *sigma_parm_max)")
    lines.append("{")
    lines.append("    int sigma_bound_ok = 0;")
    lines.append("")
    for i in range(n_param):
        lines.append(f"    sigma_parm_min[{i}] = sigma_scale_min * (para{i}_max - para{i}_min);")
    lines.append("")
    for i in range(n_param):
        lines.append(f"    sigma_parm_max[{i}] = sigma_scale_max * (para{i}_max - para{i}_min);")
    lines.append("")
    lines.append("    for (int i=0; i<N_parm; i++)")
    lines.append("    {")
    lines.append("        // each of the following cases is an error")
    lines.append("        if (sigma_parm_min[i] < 0)")
    lines.append("        {")
    lines.append("            sigma_bound_ok++;")
    lines.append("        }")
    lines.append("        if (sigma_parm_max[i] < 0)")
    lines.append("        {")
    lines.append("            sigma_bound_ok++;")
    lines.append("        }")
    lines.append("        if ( (sigma_parm_max[i]-sigma_parm_min[i]) < 0)")
    lines.append("        {")
    lines.append("            sigma_bound_ok++;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    if (sigma_bound_ok > 0)")
    lines.append("    {")
    lines.append("        printf(\"ERR: bad sigma_parm_min/max %d TIMES!\\n\", sigma_bound_ok);")
    lines.append("        return 1;")
    lines.append("    }")
    lines.append("    else")
    lines.append("    {")
    lines.append("        return 0;")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)


def init_gaussian_proposal(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 6: init gaussian proposal"))
    lines.append("////////////////////////////////////////////")
    lines.append("////////////////////////////////////////////")
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    lines.append("// set init gaussian proposal for the sampling")
    lines.append("int init_gaussian_proposal(double *ptr_sigma_prop, double init_gp_ratio)")
    lines.append("{")
    for i in range(n_param):
        if i == 0:
            lines.append(f"    *(ptr_sigma_prop) = (para{i}_max - para{i}_min) * init_gp_ratio;")
        else:
            lines.append(f"    *(ptr_sigma_prop+{i}) = (para{i}_max - para{i}_min) * init_gp_ratio;")
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines)


def para_boundary(n_param: int) -> str:
    lines: List[str] = []
    lines.append(section("Part 6: check if a proposed point is within the range"))
    lines.append("////////////////////////////////////////////")
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    lines.append("int para_boundary(double *ptr_one_chain_new)")
    lines.append("{")
    lines.append("    // PingPong outliers inside the allowed prior range")
    lines.append("    int debug = 0; // output debug infos")
    lines.append("    //")
    for i in range(n_param):
        if i == 0:
            lines.append(f"    *ptr_one_chain_new = bounce_inside(*ptr_one_chain_new, para{i}_min, para{i}_max);")
        else:
            lines.append(f"    *(ptr_one_chain_new+{i}) = bounce_inside(*(ptr_one_chain_new+{i}), para{i}_min, para{i}_max);")
    lines.append("    //")
    lines.append("    if (debug)")
    lines.append("    {")
    for i in range(n_param):
        lines.append(f"        save_debug_para_boundary(\"para{i}\", *(ptr_one_chain_new+{i}), para{i}_min, para{i}_max);")
    lines.append("    }")
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines)


def prior_function_uniform(i: int) -> str:
    return f"""/////////////////////////
double prior_para{i}(double para{i}_min, double para{i}_max)
{{
    return 1/(para{i}_max-para{i}_min);
}}
//"""


def prior_function_beta(i: int) -> str:
    return f"""/////////////////////////
double prior_para{i}(double para{i}, double para{i}_min, double para{i}_max)
{{
    // Beta distribution parameters: Beta(0.867, 3.03)
    double alpha = 0.867;
    double beta = 3.03;

    // Map from [para_min, para_max] to [0, 1]
    double x = (para{i} - para{i}_min) / (para{i}_max - para{i}_min);

    double gamma_alpha = tgamma(alpha);
    double gamma_beta = tgamma(beta);
    double gamma_alpha_beta = tgamma(alpha + beta);

    double B_alpha_beta = gamma_alpha * gamma_beta / gamma_alpha_beta;

    double beta_density = 0.0;
    if (x > 0.0 && x < 1.0) {{
        beta_density = pow(x, alpha - 1.0) * pow(1.0 - x, beta - 1.0) / B_alpha_beta;
    }} else if (x == 0.0 && alpha > 1.0) {{
        beta_density = 0.0;
    }} else if (x == 1.0 && beta > 1.0) {{
        beta_density = 0.0;
    }} else if (x == 0.0 && alpha == 1.0) {{
        beta_density = beta;
    }} else if (x == 1.0 && beta == 1.0) {{
        beta_density = alpha;
    }}

    // Change of variables: p(y) = p(x) * |dx/dy| = p(x)/(max-min)
    double jacobian = 1.0 / (para{i}_max - para{i}_min);

    return beta_density * jacobian;
}}
//"""


def prior_function_trunc_gaussian(i: int) -> str:
    return f"""/////////////////////////
double prior_para{i}(double para{i}, double para{i}_min, double para{i}_max)
{{
    double range = para{i}_max - para{i}_min;
    double sigma = range / 10.0;
    double mu = (para{i}_min + para{i}_max) / 2.0;

    if (para{i} < para{i}_min || para{i} > para{i}_max) {{
        return 0.0;
    }}

    double exponent = -0.5 * pow((para{i} - mu) / sigma, 2);
    double gaussian_pdf = exp(exponent) / (sigma * sqrt(2 * PI));

    double z_min = (para{i}_min - mu) / sigma;
    double z_max = (para{i}_max - mu) / sigma;
    double normalization = 0.5 * (erf(z_max / sqrt(2)) - erf(z_min / sqrt(2)));

    return gaussian_pdf / normalization;
}}
//"""


def prior_functions(n_param: int, prior_map: Dict[int, str]) -> str:
    lines: List[str] = []
    lines.append(section("Part 7: log prior"))
    lines.append("///////   NOTE: Write your own prior function of all parameters")
    lines.append("///////")
    lines.append("////////////////////////////////////////////")
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    lines.append("// NOTE: para_boundary ensures: ((a<=a_max) && (a>=a_min))")
    lines.append("//")
    lines.append("////////////////////////////////////////////")
    lines.append("/*")
    lines.append(" * Supported priors generated here:")
    lines.append(" *   uniform")
    lines.append(" *   beta: fixed Beta(0.867, 3.03), mapped to [para_min, para_max]")
    lines.append(" *   trunc_gaussian: mu=(min+max)/2, sigma=(max-min)/10, truncated to [min,max]")
    lines.append(" */")
    lines.append("//")

    for i in range(n_param):
        kind = prior_map[i]
        if kind == "uniform":
            lines.append(prior_function_uniform(i))
        elif kind == "beta":
            lines.append(prior_function_beta(i))
        elif kind == "trunc_gaussian":
            lines.append(prior_function_trunc_gaussian(i))
        else:
            raise ValueError(f"Unsupported prior type for para{i}: {kind}")
    return "\n".join(lines)


def log_prior_function(n_param: int, prior_map: Dict[int, str]) -> str:
    lines: List[str] = []
    lines.append(section("Part 8: Combine all prior distributions"))
    lines.append("////////////////////////////////////////////")
    lines.append("//")
    lines.append("double log_prior(double *ptr_one_chain)")
    lines.append("{")
    lines.append("    //")
    for i in range(n_param):
        lines.append(f"    double para{i};")
    lines.append("")
    lines.append("    double log_prior;")
    lines.append("    int debug = 0; // output debug infos")
    lines.append("    //")
    for i in range(n_param):
        if i == 0:
            lines.append(f"    para{i} = *ptr_one_chain;")
        else:
            lines.append(f"    para{i} = *(ptr_one_chain+{i});")
    lines.append("")
    lines.append("    //")
    terms: List[str] = []
    for i in range(n_param):
        kind = prior_map[i]
        if kind == "uniform":
            terms.append(f"log(prior_para{i}(para{i}_min, para{i}_max))")
        else:
            terms.append(f"log(prior_para{i}(para{i}, para{i}_min, para{i}_max))")

    for j, term in enumerate(terms):
        prefix = "    log_prior = " if j == 0 else "                "
        suffix = " +" if j < len(terms) - 1 else " ;"
        lines.append(prefix + term + suffix)
    lines.append("    //")
    lines.append("    if (debug)")
    lines.append("    {")
    fmt = ",".join([f"para{i}" for i in range(n_param)])
    placeholders = " ".join(["%lf" for _ in range(n_param)])
    args = ", ".join([f"para{i}" for i in range(n_param)])
    lines.append(f"        printf(\"{fmt}: {placeholders}\\n\", {args});")
    lines.append("    }")
    lines.append("    //")
    lines.append("    return log_prior;")
    lines.append("}")
    return "\n".join(lines)


def save_debug_function() -> str:
    return r'''


////////////////////////////////////////////
////////////////////////////////////////////
/////  Save para debug
/////  NO need to change
////////////////////////////////////////////
////////////////////////////////////////////
//
int save_debug_para_boundary(char *p_s, double p, double p_min, double p_max)
{
    FILE *out;
    //
    // set fnames
    char fname[100];

    snprintf(fname, sizeof fname, "%s%s%s%s", results_dir, "/", p_s, ".debug_para_boundary");
    //
    // open files
    if ((out = fopen(fname, "a")) == NULL)
    {
        fprintf(stderr, "Can't create output file!\n");
        exit(3);
    }
    //
    fprintf(out, "%f", p);
    fprintf(out, "  ");
    fprintf(out, "%f", p_min);
    fprintf(out, "  ");
    fprintf(out, "%f", p_max);
    fprintf(out, "\n");
    //
    // close files
    if (fclose(out) != 0)
        fprintf(stderr, "Error in closing file!\n");
    //
    return 0;
}
'''.strip()


def generate_c_code(n_param: int, prior_map: Dict[int, str]) -> str:
    """Generate the complete user_prior.c source."""
    validate_prior_map(n_param, prior_map)

    parts: List[str] = []
    parts.append(c_header_autogenerated(n_param, prior_map))
    parts.append(r'''
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

#define PI 3.14159265358979323846
#define DEST_SIZE 100

//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
////// Part 0
////// General part, no need to change in most cases
//////////////////////////////////////////////////////////////////////////////
//
// Number of parameters
extern int N_parm;
//
// Gaussian proposal array
double *sigma_parm_min;
double *sigma_parm_max;
//
// Range to scale gaussian proposal
extern double sigma_scale_min;
extern double sigma_scale_max;
//
// initial gaussian proposal ratio to the paramter range
extern double init_gp_ratio;
//
// Define results directory
extern char *results_dir; //dir to save outputs
//
/////////////////////////////////////
//NOTE: change log_prior in mpi_batch/init if func_prototype is changed
double log_prior(double *ptr_one_chain);
//
////////////////////
//calc sigma scale boundary (function in user_prior.c)
int calc_sigma_scale_boundary(double sigma_scale_min, double sigma_scale_max, double *sigma_parm_min, double *sigma_parm_max);
//
// useful random number genetors
double r8_normal_ab ( double a, double b );
double r8_unif_ab ( double a, double b );
double r8_logunif_ab ( double a, double b );
double normal_pdf(double x, double mean, double sd);
//
///////////////////
// prototype no need to change, contents need change
void read_parm_range(char *path);
//
///////////////////////////////////////////////
// check if modification is needed or not
///////////////////
int save_debug_para_boundary(char *p_s, double p, double p_min, double p_max);
//

double bounce_inside(double para, double para_min, double para_max)
{
    if (para > para_max)
    {
        para = para_max - (para - para_max);
        para = fmax(para, para_min);
    }
    if (para < para_min)
    {
        para = para_min + (para_min - para);
        para = fmin(para, para_max);
    }
    return para;
}
'''.strip())
    parts.append(declarations(n_param))
    parts.append(read_parm_range(n_param))
    parts.append(init_functions(n_param))
    parts.append(init_parm_set(n_param))
    parts.append(sigma_boundary(n_param))
    parts.append(init_gaussian_proposal(n_param))
    parts.append(para_boundary(n_param))
    parts.append(prior_functions(n_param, prior_map))
    parts.append(log_prior_function(n_param, prior_map))
    parts.append(save_debug_function())
    parts.append("")
    return "\n\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a complete Nii-C-style user_prior.c file."
    )
    parser.add_argument(
        "--n-param",
        type=int,
        default=None,
        help="Number of sampled parameters. If omitted, use N_PARAM in this script.",
    )
    parser.add_argument(
        "--beta",
        type=str,
        default=None,
        help="Comma/space-separated parameter indices using Beta(0.867,3.03), e.g. '1,8'.",
    )
    parser.add_argument(
        "--trunc-gaussian",
        type=str,
        default=None,
        help="Comma/space-separated parameter indices using truncated Gaussian, e.g. '0,7'.",
    )
    parser.add_argument(
        "--uniform",
        type=str,
        default=None,
        help="Comma/space-separated parameter indices forced to uniform. Overrides config.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output C filename. If omitted, use OUTPUT_C_FILE in this script.",
    )
    args = parser.parse_args()

    n_param = args.n_param if args.n_param is not None else N_PARAM
    output = args.output if args.output is not None else OUTPUT_C_FILE

    beta_indices = parse_index_list(args.beta) if args.beta is not None else None
    trunc_indices = parse_index_list(args.trunc_gaussian) if args.trunc_gaussian is not None else None
    uniform_indices = parse_index_list(args.uniform) if args.uniform is not None else None

    prior_map = build_prior_map(
        n_param=n_param,
        base_map=PRIOR_TYPES,
        beta_indices=beta_indices,
        trunc_gaussian_indices=trunc_indices,
        uniform_indices=uniform_indices,
    )

    c_code = generate_c_code(n_param, prior_map)
    Path(output).write_text(c_code, encoding="utf-8")

    print(f"Generated {output}")
    print(f"N_PARAM = {n_param}")
    print("Prior assignment:")
    for i in range(n_param):
        print(f"  para{i}: {prior_map[i]}")
    print("")
    print("Reminder: make sure N_parm in input.ini/readin configuration matches N_PARAM.")


if __name__ == "__main__":
    main()
