# Chain grid
N_iter:                 1000000
N_beta:                 8
Beta_Values:            0.005, 0.015, 0.04, 0.10, 0.25, 0.50, 0.78, 1.0

# Ladder and proposal control
Tune_Ladder:            0
N_stopTuneLadder:       300000
scale_tune_ladder:      0.2
zero_stretch:           0.1
n_iter_a_stack:         5000
n_iter_a_batch_base:    20
n_iter_a_batch_rand:    5
N_swap:                 1
Swapmode:               1
N_stoptune:             10000000
N_begintune:            0
n_iter_in_tune:         1000
ar_ok_lower:            0.10
ar_ok_upper:            0.45
ar_best:                0.23
ar_accept_diff:         0.1
sigma_scale_half_ratio: 20
sigma_scale_min:        0.0000000005
sigma_scale_max:        0.2
sigma_jumpin_ratio:     300

# Initialisation and output
i_save_begin:           0
init_rand_seed:         9
init_gp_ratio:          0.1
Fout_Len:               100
FoutPre:                chain
FoutSuf:                .dat
results_dir:            chains

# Data
Data_file:              input.dat
ndim_data:              13
Delimiter:              blank

Mstar_Msun:             1.32

N_parm:                 17

# Priors
############ Planet 1
para0_min:    9000
para0_max:    9800    # P1_days

para1_min:    0.0
para1_max:    0.99           # e1

para2_min:    1.0e-3
para2_max:    30          # Mp1_Mjup

para3_min:    0.0
para3_max:    1.0         # tau1 at t_ref_jd

para4_min:    0.0
para4_max:    360.0         # omega1_deg

para5_min:   -1
para5_max:   1           # cosi1

para6_min:    0.0
para6_max:   360.0         # Omega1_deg

############ Planet 2
para7_min:    1600
para7_max:    2600    # P2_days

para8_min:    0.0
para8_max:    0.9           # e2

para9_min:    1.0e-3
para9_max:    30          # Mp2_Mjup

para10_min:   0.0
para10_max:   1.0         # tau2 at t_ref_jd

para11_min:   0.0
para11_max:   360.0         # omega2_deg

para12_min:  -1
para12_max:  1           # cosi2

para13_min:   0.0
para13_max:   360.0         # Omega2_deg

############ Absolute astrometric nuisance/base terms
para14_min:  10
para14_max:  40           # plx_total_mas

para15_min:  0
para15_max:  1           # sigma_jit_AL_mas

para16_min:  0
para16_max:  1           # sigma_jit_IMG_mas

